// ── launchApp: same logic as landing page ──
function launchApp(e) {
  if (e) e.preventDefault();
  if (typeof Auth !== 'undefined' && Auth.isLoggedIn && Auth.isLoggedIn()) {
    window.location.href = '/livecam';
  } else {
    window.location.href = '/login';
  }
}

// ── Auth loader ──
(function(){var s=document.createElement('script');s.src='script/auth.js';s.onerror=function(){window.__authJsFailed=true;};document.head.appendChild(s);})();

// ── Feedback logic ──
let rating=0,category="General";
window.addEventListener('DOMContentLoaded',()=>{try{const token=localStorage.getItem('ea_access_token');if(token){fetch('/auth/me',{headers:{'Authorization':'Bearer '+token}}).then(r=>r.ok?r.json():null).then(me=>{if(me&&me.username){const inp=document.getElementById('usernameInput');inp.value=me.username;inp.readOnly=true;inp.style.background='var(--elevated)';inp.style.color='var(--text2)';}}).catch(()=>{});}}catch(_){}});
function setRating(r){rating=r;const btns=[...document.querySelectorAll('.star-btn')];btns.forEach((b,i)=>{b.classList.toggle('lit',i<r);b.classList.remove('preview');});}
// hover preview
(function(){function applyPreview(btns,lit,prev){btns.forEach((b,i)=>{b.classList.toggle('lit',i<lit);b.classList.toggle('preview',i>=lit&&i<prev);});}document.addEventListener('DOMContentLoaded',function(){const btns=[...document.querySelectorAll('.star-btn')];btns.forEach((btn,idx)=>{btn.addEventListener('mouseenter',()=>applyPreview(btns,rating,idx+1));btn.addEventListener('mouseleave',()=>applyPreview(btns,rating,0));});});})();
function selectChip(el){document.querySelectorAll('.chip').forEach(c=>c.classList.remove('active'));el.classList.add('active');category=el.textContent.trim();}
function showError(msg){const el=document.getElementById('errorMsg');el.textContent=msg;el.classList.add('show');}
function hideError(){const el=document.getElementById('errorMsg');el.textContent='';el.classList.remove('show');}
function setLoading(loading){const btn=document.getElementById('submitBtn');if(loading){btn.disabled=true;btn.innerHTML='<div class="spinner"></div> Sending…';}else{btn.disabled=false;btn.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke-linecap="round" stroke-linejoin="round"><line x1="22" y1="2" x2="11" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></svg> Send Feedback';}}
async function submitFeedback(){hideError();const username=document.getElementById('usernameInput').value.trim();const email=document.getElementById('emailInput').value.trim();const text=document.getElementById('feedbackText').value.trim();if(!username){document.getElementById('usernameInput').focus();document.getElementById('usernameInput').style.borderColor='var(--accent)';showError('Please enter your username before submitting.');return;}document.getElementById('usernameInput').style.borderColor='';if(!text){document.getElementById('feedbackText').focus();document.getElementById('feedbackText').style.borderColor='var(--accent)';showError('Please write your feedback before submitting.');return;}document.getElementById('feedbackText').style.borderColor='';if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)){document.getElementById('emailInput').focus();document.getElementById('emailInput').style.borderColor='var(--accent)';showError('Please enter a valid email address, or leave it blank.');return;}document.getElementById('emailInput').style.borderColor='';const payload={username,email:email||null,rating:rating>0?rating:null,category,message:text};setLoading(true);try{let token=null;try{if(typeof Auth!=='undefined'&&Auth.getAccessToken)token=Auth.getAccessToken();}catch(_){}if(!token)token=localStorage.getItem('ea_access_token');const headers={'Content-Type':'application/json'};if(token)headers['Authorization']='Bearer '+token;let res;try{res=await fetch('/api/feedback',{method:'POST',headers,body:JSON.stringify(payload)});}catch(e){res=await fetch('/feedback',{method:'POST',headers,body:JSON.stringify(payload)});}if(!res.ok){let errMsg=`Server error (${res.status}). Please try again.`;try{const d=await res.json();if(d.detail)errMsg=d.detail;else if(d.message)errMsg=d.message;}catch(_){}throw new Error(errMsg);}document.getElementById('formContent').style.display='none';document.getElementById('successState').classList.add('show');}catch(err){showError(err.message||'Failed to submit feedback. Please try again.');}finally{setLoading(false);}}
(function(){var btn=document.getElementById('hamburgerBtn'),closeBtn=document.getElementById('drawerCloseBtn'),drawer=document.getElementById('mobileDrawer'),overlay=document.getElementById('mobileOverlay');if(!btn)return;function openD(){btn.classList.add('open');drawer.classList.add('open');overlay.classList.add('open');btn.setAttribute('aria-expanded','true');document.body.style.overflow='hidden';}function closeD(){btn.classList.remove('open');drawer.classList.remove('open');overlay.classList.remove('open');btn.setAttribute('aria-expanded','false');document.body.style.overflow='';}btn.addEventListener('click',function(){btn.classList.contains('open')?closeD():openD();});if(closeBtn)closeBtn.addEventListener('click',closeD);if(overlay)overlay.addEventListener('click',closeD);document.addEventListener('keydown',function(e){if(e.key==='Escape')closeD();});if(drawer)drawer.querySelectorAll('a').forEach(function(el){el.addEventListener('click',closeD);});})();
function resetForm(){rating=0;category='General';hideError();document.getElementById('feedbackText').value='';document.getElementById('feedbackText').style.borderColor='';const unameInp=document.getElementById('usernameInput');if(!unameInp.readOnly)unameInp.value='';unameInp.style.borderColor='';document.getElementById('emailInput').value='';document.getElementById('emailInput').style.borderColor='';document.querySelectorAll('.star-btn').forEach(b=>{b.classList.remove('lit');b.classList.remove('preview');});document.querySelectorAll('.chip').forEach(c=>c.classList.remove('active'));document.querySelector('.chip').classList.add('active');document.getElementById('formContent').style.display='block';document.getElementById('successState').classList.remove('show');}